server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    bus.amqp.enabled: false
    config:
      enabled: false
      failFast: true
      server:
        git :
          uri: https://bitbucket.org/juniorcodebreakers/configurations.git
          ignore-local-ssh-settings: true
          private-key: |
                        -----BEGIN OPENSSH PRIVATE KEY-----
                        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
                        NhAAAAAwEAAQAAAQEArK2JMKOJ6MyJaK9yJPm26ceHUathdNv8kCvorFVc8T81VsnY99OB
                        mts8hAqJ67DjJkMhwVF85bQAxM3IxOM1dQ93Q90JqZEnBmxZh/QUz6MPfQHF/lCks+pzFT
                        A+HsgGCcm5+i/W51WUNhDlXvTpDsBChltwabs085y7dySAkmDDauCON4MZb3KAj8WSuIxi
                        yX6EJnI8j1oPcpFhl29RN6cU0SHPD6kuGsN7gWRF8dV2NAl8ypHoysNktfzRK5xUlN0lsH
                        FB071VhiWyqsTXB5hbSlR6b6WXe6KybWQnnJaNc9w8ES9h+aD2iUuPCqkXRuNeTkFJRRDL
                        HgjfBlUjSQAAA9i3gO5Vt4DuVQAAAAdzc2gtcnNhAAABAQCsrYkwo4nozIlor3Ik+bbpx4
                        dRq2F02/yQK+isVVzxPzVWydj304Ga2zyEConrsOMmQyHBUXzltADEzcjE4zV1D3dD3Qmp
                        kScGbFmH9BTPow99AcX+UKSz6nMVMD4eyAYJybn6L9bnVZQ2EOVe9OkOwEKGW3BpuzTznL
                        t3JICSYMNq4I43gxlvcoCPxZK4jGLJfoQmcjyPWg9ykWGXb1E3pxTRIc8PqS4aw3uBZEXx
                        1XY0CXzKkejKw2S1/NErnFSU3SWwcUHTvVWGJbKqxNcHmFtKVHpvpZd7orJtZCeclo1z3D
                        wRL2H5oPaJS48KqRdG415OQUlFEMseCN8GVSNJAAAAAwEAAQAAAQEAoDfD+yVCaIafWEqx
                        li080l0X6Wci3dLf3MVg9cWenxkO3KAceJX+wzh4ReuhXNabbH0NbNm3EUqbDAAEMOrARw
                        U6m/UTagoMM6GE0OhgBug9Drf+haE9sNHwRdClUto1AA/0R3br52k4Q5IZwKltNQqerxtY
                        ikHxN7hNGJb91NH8n45Pr+RnQBI44eC5e8QhBCQxqLnKFUrhMqANyX6lbNbY3K9oE1PJh4
                        YH0v6CHIZq95eqeNBQuVUKHBOmtzi8QRbuzjGxD774IgDlJZnZ8tJ9G2L5v3XiK3i63IEA
                        1ChZjbnwqqz4kVi3pJFeScTQOg0XfWXlehhWmJxUlKmKoQAAAIEAhhF48Tr41hR3Slr/nt
                        0LaY4bgvF/iyn/GJZpCjaYNJcGLfJk7+ok0Ja+l658DCzRpKKa1DduotALeD3h5k8j4cx/
                        k7c2UnhrqluOZlViv+7Ge94kq8PG2zFbut9a+mg/HOZOKphz+tUwzj1bgAKPWWQzrm8fzC
                        3njJru10Uo2hwAAACBAN9TIk26OC8/nj8x/uAJKGWulxn3zLW1jTgKhz7tfddmZ3WZn0H9
                        nITZSTp3eY2qQ2V3Rn9myZ1na/8Spv4jI1P4nUdFioRr0xPghwMtLUcDvzGpElL8aFy2uE
                        7uUsv7NmUPuwN5T600Y7Ukz5NWFAxsw7C86pJmFQLr9QYdFMCfAAAAgQDF8V6awkBpCis/
                        BnAPN98AM9a4B3ZlnNpAmU7OhnW1C6GbKQ9p3RatYmsRNYoJkd2tuihBltzmaL1Uyx7Y4Z
                        vHahY9tbO317tXTIhTYfqVP9jTfGmSTktEZVqVQMcSUkpgaKDOjMT8AqHRsCiUf1JH2dT4
                        Qk2kcr70E40j2C8LFwAAABtrb3lvdEBvbGRrb3lvdC1sYXB0b3AubG9jYWwBAgMEBQY=
                        -----END OPENSSH PRIVATE KEY-----
